/* KrishiSetu - js/forms.js */
function escapeHtml(s){if(!s)return'';return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
async function uploadImage(el){if(!el||!el.files||!el.files[0])return null;try{const r=await apiUpload(el.files[0]);return r.url;}catch(e){showToast('Upload failed: '+e.message);return null;}}
function initDropzone(zoneId,inputId){const z=document.getElementById(zoneId);const i=document.getElementById(inputId);if(!z||!i)return;z.addEventListener('click',()=>i.click());i.addEventListener('change',()=>{if(i.files[0])z.innerHTML='<img src="'+URL.createObjectURL(i.files[0])+'" style="width:100%;max-height:200px;object-fit:cover;border-radius:8px;">';});}
initDropzone('dropzoneLand','landPhotoInput');
initDropzone('dropzoneEquip','equipPhotoInput');

// ===== LAND =====
async function loadLandListings(search=''){
  const c=document.getElementById('landGridContainer');const cl=document.getElementById('landCountLabel');if(!c)return;
  try{const p=search?'search='+encodeURIComponent(search):'';const d=await getLand(p);cl.textContent=d.count+' Listing'+(d.count!==1?'s':'');
  if(!d.listings.length){c.innerHTML='<p style="padding:24px;text-align:center;color:#64748b;">No land listings found.</p>';return;}
  c.innerHTML=d.listings.map(l=>{const t=escapeHtml(l.title),loc=escapeHtml(l.location),dist=escapeHtml(l.district||''),soil=escapeHtml(l.soil_type||''),water=escapeHtml(l.water_source||'');const price=((l.price_per_season||l.price_per_month||l.price_per_year)||0).toLocaleString();const lt=escapeHtml(l.lease_type||'Season');return `<div class="equip-card"><div class="equip-img-wrap">${l.photo_url?`<img src="${l.photo_url}" alt="${t}" class="equip-img" />`:`<div style="height:180px;background:#e2e8f0;display:flex;align-items:center;justify-content:center;font-size:48px;">🌾</div>`}</div><div class="equip-body"><h3 class="equip-title">${t}</h3><div class="equip-location">📍 ${loc}${dist?', '+dist:''}</div><div class="land-tags-row"><span class="tag-pill tag-green">${l.area_acres} Acres</span>${soil?`<span class="tag-pill tag-orange">${soil}</span>`:''}${water?`<span class="tag-pill tag-blue">💧 ${water}</span>`:''}</div><div class="equip-footer-row"><div class="equip-price-box"><span class="price-hr" style="color:#16a34a;">₹ ${price}<span class="price-period">/${lt}</span></span></div><button onclick="bookItem('land',${l.id},this.dataset.title,${l.price_per_season||l.price_per_month||l.price_per_year||0})" data-title="${t}" class="btn-list" style="background:#16a34a;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;">Book</button></div></div></div>`;}).join('');
  }catch(e){c.innerHTML='<p style="padding:24px;text-align:center;color:#dc2626;">Error loading listings.</p>';}
}

document.getElementById('formListLand')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const photo_url=await uploadImage(document.getElementById('landPhotoInput'));await createLand({title:document.getElementById('landFormTitle').value,area_acres:Number(document.getElementById('landFormArea').value),lease_type:document.getElementById('landFormLeaseType').value,price_per_season:Number(document.getElementById('landFormPerSeason').value)||null,price_per_year:Number(document.getElementById('landFormPerYear').value)||null,location:document.getElementById('landFormLocation').value,district:document.getElementById('landFormDistrict').value||null,state:document.getElementById('landFormState').value||null,soil_type:document.getElementById('landFormSoilType').value,water_source:document.getElementById('landFormWaterSource').value,description:document.getElementById('landFormDesc').value||null,photo_url});showToast('Land listing created!');navigateTo('view-land-leasing');loadLandListings();}catch(e){showToast('Error: '+e.message);}});

// ===== EQUIPMENT =====
async function loadEquipmentListings(search=''){const c=document.getElementById('equipGridContainer');const cl=document.getElementById('equipCountLabel');if(!c)return;try{const p=search?'search='+encodeURIComponent(search):'';const d=await getEquipment(p);cl.textContent=d.count+' Listing'+(d.count!==1?'s':'');if(!d.listings.length){c.innerHTML='<p style="padding:24px;text-align:center;color:#64748b;">No equipment found.</p>';return;}c.innerHTML=d.listings.map(e=>{const nm=escapeHtml(e.name),tp=escapeHtml(e.type),loc=escapeHtml(e.location),dist=escapeHtml(e.district||'');return `<div class="equip-card"><div class="equip-img-wrap">${e.photo_url?`<img src="${e.photo_url}" alt="${nm}" class="equip-img" />`:`<div style="height:180px;background:#e2e8f0;display:flex;align-items:center;justify-content:center;font-size:48px;">🚜</div>`}</div><div class="equip-body"><h3 class="equip-title">${nm}</h3><span class="equip-tag">${tp}</span><div class="equip-location">📍 ${loc}${dist?', '+dist:''}</div>${e.with_operator?'<div class="equip-operator">👤 With Operator</div>':''}<div class="equip-footer-row"><div class="equip-price-box"><span class="price-hr">₹ ${e.price_per_hour||0}<span class="price-period">/hr</span></span><span class="price-day">₹ ${(e.price_per_day||0).toLocaleString()}/day</span></div><button onclick="bookItem('equipment',${e.id},this.dataset.title,${e.price_per_day||0})" data-title="${nm}" class="btn-list" style="background:#ea580c;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;">Book</button></div></div></div>`;}).join('');}catch(e){c.innerHTML='<p style="padding:24px;text-align:center;color:#dc2626;">Error loading.</p>';}}

document.getElementById('formListEquipment')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const photo_url=await uploadImage(document.getElementById('equipPhotoInput'));await createEquipment({name:document.getElementById('equipFormName').value,type:document.getElementById('equipFormType').value,price_per_hour:Number(document.getElementById('equipFormPerHour').value)||null,price_per_day:Number(document.getElementById('equipFormPerDay').value)||null,location:document.getElementById('equipFormLocation').value,district:document.getElementById('equipFormDistrict').value||null,state:document.getElementById('equipFormState').value||null,with_operator:document.getElementById('equipFormOperator').checked,description:document.getElementById('equipFormDesc').value||null,photo_url});showToast('Equipment listed!');navigateTo('view-equipment-rental');loadEquipmentListings();}catch(e){showToast('Error: '+e.message);}});

// ===== LABOUR =====
async function loadLabourListings(search=''){const c=document.getElementById('labourGridContainer');const cl=document.getElementById('labourCountLabel');if(!c)return;try{const p=search?'search='+encodeURIComponent(search):'';const d=await getLabour(p);cl.textContent=d.count+' Listing'+(d.count!==1?'s':'');if(!d.listings.length){c.innerHTML='<p style="padding:24px;text-align:center;color:#64748b;">No labour services found.</p>';return;}c.innerHTML=d.listings.map(l=>{const t=escapeHtml(l.title),loc=escapeHtml(l.location),dist=escapeHtml(l.district||''),sk=escapeHtml(l.skills||'');return `<div class="equip-card"><div class="equip-img-wrap"><div style="height:180px;background:linear-gradient(135deg,#7c3aed,#a78bfa);display:flex;align-items:center;justify-content:center;font-size:48px;">👷</div></div><div class="equip-body"><h3 class="equip-title">${t}</h3><div class="equip-location">📍 ${loc}${dist?', '+dist:''}</div>${sk?`<div style="margin:4px 0;"><span class="equip-tag" style="background:#ede9fe;color:#7c3aed;">${sk}</span></div>`:''}<div class="equip-footer-row"><div class="equip-price-box"><span class="price-hr" style="color:#7c3aed;">₹ ${l.daily_rate||0}<span class="price-period">/day</span></span></div><button onclick="bookItem('labour',${l.id},this.dataset.title,${l.daily_rate||0})" data-title="${t}" class="btn-list" style="background:#7c3aed;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;">Hire</button></div></div></div>`;}).join('');}catch(e){c.innerHTML='<p style="padding:24px;text-align:center;color:#dc2626;">Error loading.</p>';}}

document.getElementById('formListLabour')?.addEventListener('submit',async(e)=>{e.preventDefault();try{await createLabour({title:document.getElementById('labourFormTitle').value,skills:document.getElementById('labourFormSkills').value||null,experience_years:Number(document.getElementById('labourFormExperience').value)||0,daily_rate:Number(document.getElementById('labourFormDailyRate').value)||null,location:document.getElementById('labourFormLocation').value,description:document.getElementById('labourFormDesc').value||null});showToast('Labour listed!');navigateTo('view-labour');loadLabourListings();}catch(e){showToast('Error: '+e.message);}});

// ===== PRODUCE =====
async function loadProduceListings(search=''){const c=document.getElementById('produceGridContainer');const cl=document.getElementById('produceCountLabel');if(!c)return;try{const p=search?'search='+encodeURIComponent(search):'';const d=await getProduce(p);cl.textContent=d.count+' Listing'+(d.count!==1?'s':'');if(!d.listings.length){c.innerHTML='<p style="padding:24px;text-align:center;color:#64748b;">No produce listed.</p>';return;}c.innerHTML=d.listings.map(p=>{const cn=escapeHtml(p.crop_name),loc=escapeHtml(p.location),dist=escapeHtml(p.district||''),unit=escapeHtml(p.unit);return `<div class="equip-card"><div class="equip-img-wrap"><div style="height:180px;background:linear-gradient(135deg,#d97706,#fbbf24);display:flex;align-items:center;justify-content:center;font-size:48px;">🌾</div></div><div class="equip-body"><h3 class="equip-title">${cn}</h3><div class="equip-location">📍 ${loc}${dist?', '+dist:''}</div><div style="margin:4px 0;"><span class="equip-tag" style="background:#fef3c7;color:#92400e;">${p.quantity} ${unit}</span><span class="equip-tag">Grade ${escapeHtml(p.quality_grade)}</span></div><div class="equip-footer-row"><div class="equip-price-box"><span class="price-hr" style="color:#d97706;">₹ ${p.price_per_unit}<span class="price-period">/${unit}</span></span></div><button onclick="bookItem('produce',${p.id},this.dataset.title,${p.price_per_unit})" data-title="${cn}" class="btn-list" style="background:#d97706;color:#fff;border:none;padding:6px 14px;border-radius:6px;cursor:pointer;">Buy</button></div></div></div>`;}).join('');}catch(e){c.innerHTML='<p style="padding:24px;text-align:center;color:#dc2626;">Error loading.</p>';}}

document.getElementById('formListProduce')?.addEventListener('submit',async(e)=>{e.preventDefault();try{await createProduce({crop_name:document.getElementById('produceFormCropName').value,quantity:Number(document.getElementById('produceFormQuantity').value),unit:document.getElementById('produceFormUnit').value,price_per_unit:Number(document.getElementById('produceFormPrice').value),quality_grade:document.getElementById('produceFormGrade').value,location:document.getElementById('produceFormLocation').value,description:document.getElementById('produceFormDesc').value||null});showToast('Produce listed!');navigateTo('view-produce');loadProduceListings();}catch(e){showToast('Error: '+e.message);}});

// ===== BOOKINGS =====
async function bookItem(type,id,title,price){if(!getUser()){showToast('Please sign in first.');navigateTo('view-signin');return;}if(!confirm('Book "'+title+'"?'))return;try{await createBooking({listing_type:type,listing_id:id});showToast('Booking created!');}catch(e){showToast('Error: '+e.message);}}
async function loadBookings(){const o=document.getElementById('bookingsOutgoingList');const i=document.getElementById('bookingsIncomingList');if(!o||!i)return;try{const my=await getMyBookings();o.innerHTML=my.bookings.length?my.bookings.map(renderBooking).join(''):'<p style="padding:24px;text-align:center;color:#64748b;">No bookings yet.</p>';}catch(e){o.innerHTML='<p style="color:#dc2626;">Error.</p>';}try{const inc=await getIncomingBookings();i.innerHTML=inc.bookings.length?inc.bookings.map(renderBooking).join(''):'<p style="padding:24px;text-align:center;color:#64748b;">No incoming.</p>';}catch(e){i.innerHTML='<p style="color:#dc2626;">Error.</p>';}}
function renderBooking(b){const sc={pending:'#eab308',confirmed:'#3b82f6',active:'#16a34a',completed:'#6b7280',cancelled:'#dc2626'};const t=escapeHtml(b.listing_title||b.listing_type);return `<div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-bottom:12px;"><div style="display:flex;justify-content:space-between;align-items:center;"><div><strong>${t}</strong><br><span style="color:#64748b;font-size:13px;">${escapeHtml(b.listing_type)} ${escapeHtml(b.status)}</span></div><span style="color:${sc[b.status]||'#6b7280'};font-weight:600;font-size:13px;">${escapeHtml(b.status.toUpperCase())}</span></div><div style="margin-top:8px;font-size:14px;">₹${b.total_price.toLocaleString()}</div><div style="margin-top:8px;display:flex;gap:6px;">${b.status==='pending'?`<button onclick="updateBookingStatus(${b.id},'confirmed')" style="background:#3b82f6;color:#fff;border:none;padding:4px 10px;border-radius:6px;font-size:12px;cursor:pointer;">Confirm</button>`:''}${b.status!=='cancelled'&&b.status!=='completed'?`<button onclick="updateBookingStatus(${b.id},'cancelled')" style="background:#dc2626;color:#fff;border:none;padding:4px 10px;border-radius:6px;font-size:12px;cursor:pointer;">Cancel</button>`:''}</div></div>`;}
async function updateBookingStatus(id,status){try{await updateBooking(id,{status});showToast('Updated!');loadBookings();}catch(e){showToast('Error: '+e.message);}}

// ===== MESSAGES =====
let currentChatUserId=null;
async function loadConversations(){const c=document.getElementById('conversationsList');if(!c)return;try{const d=await getConversations();c.innerHTML=d.conversations.length?d.conversations.map(cv=>{const un=escapeHtml(cv.other_username),msg=escapeHtml(cv.last_message||'');return `<div onclick="openChat(${cv.other_user_id},'${escapeHtml(cv.other_username).replace(/'/g,"\'")}')" style="padding:12px 16px;border-bottom:1px solid #e2e8f0;cursor:pointer;display:flex;justify-content:space-between;align-items:center;"><div><strong style="font-size:14px;">${un}</strong><br><span style="color:#64748b;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:180px;display:block;">${msg}</span></div>${cv.unread_count>0?`<span style="background:#0d9488;color:#fff;border-radius:50%;width:20px;height:20px;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;">${cv.unread_count}</span>`:''}</div>`;}).join(''):'<p style="padding:24px;text-align:center;color:#64748b;">No conversations yet.</p>';}catch(e){c.innerHTML='<p style="color:#dc2626;">Error.</p>';}}
async function openChat(userId,username){currentChatUserId=userId;document.getElementById('threadHeader').textContent=username;document.getElementById('threadInput').style.display='block';try{const d=await getThread(userId);const c=document.getElementById('threadMessages');const myId=getUser()?.id;c.innerHTML=d.messages.map(m=>{const isMe=m.sender_id===myId;return `<div style="display:flex;justify-content:${isMe?'flex-end':'flex-start'};margin-bottom:8px;"><div style="background:${isMe?'#0d9488':'#e2e8f0'};color:${isMe?'#fff':'#1e293b'};padding:8px 12px;border-radius:12px;max-width:70%;font-size:14px;">${escapeHtml(m.content)}</div></div>`;}).join('');c.scrollTop=c.scrollHeight;}catch(e){document.getElementById('threadMessages').innerHTML='<p>Error.</p>';}}
document.getElementById('sendMessageBtn')?.addEventListener('click',async()=>{const input=document.getElementById('messageInput');if(!input?.value.trim()||!currentChatUserId)return;try{await sendMessage({receiver_id:currentChatUserId,content:input.value.trim()});input.value='';openChat(currentChatUserId,document.getElementById('threadHeader').textContent);}catch(e){showToast('Error: '+e.message);}});

// ===== PAYMENTS =====
async function loadPayments(){const c=document.getElementById('paymentsList');if(!c)return;try{const d=await getMyPayments();const sc={held:'#eab308',released:'#16a34a',refunded:'#dc2626'};c.innerHTML=d.payments.length?d.payments.map(p=>{const lt=escapeHtml(p.listing_title||p.listing_type);const ref=escapeHtml(p.transaction_ref||'');return `<div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;"><div><strong>${lt}</strong><br><span style="color:#64748b;font-size:13px;">${ref}</span></div><div style="text-align:right;"><strong>₹${p.amount.toLocaleString()}</strong><br><span style="color:${sc[p.status]||'#6b7280'};font-size:13px;font-weight:600;">${escapeHtml(p.status.toUpperCase())}</span></div></div>`;}).join(''):'<p style="padding:24px;text-align:center;color:#64748b;">No payments yet.</p>';}catch(e){c.innerHTML='<p style="color:#dc2626;">Error.</p>';}}

// ===== PROFILE =====
async function loadProfile(){if(!getUser()){navigateTo('view-signin');return;}try{const d=await getProfile();const u=d.user;document.getElementById('profileFormUsername').value=u.username||'';document.getElementById('profileFormPhone').value=u.phone||'';document.getElementById('profileFormLocation').value=u.location||'';document.getElementById('profileFormBio').value=u.bio||'';document.getElementById('profileFormSkills').value=u.skills||'';}catch(e){showToast('Error loading profile.');}}
document.getElementById('formProfile')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const d=await updateProfile({username:document.getElementById('profileFormUsername').value,phone:document.getElementById('profileFormPhone').value,location:document.getElementById('profileFormLocation').value,bio:document.getElementById('profileFormBio').value,skills:document.getElementById('profileFormSkills').value});setUser(d.user);document.getElementById('nav-user-name').textContent=d.user.username;showToast('Profile updated!');}catch(e){showToast('Error: '+e.message);}});
document.getElementById('formChangePassword')?.addEventListener('submit',async(e)=>{e.preventDefault();try{await changePassword({current_password:document.getElementById('pwFormCurrent').value,new_password:document.getElementById('pwFormNew').value});showToast('Password changed!');document.getElementById('pwFormCurrent').value='';document.getElementById('pwFormNew').value='';}catch(e){showToast('Error: '+e.message);}});

// ===== ADMIN =====
async function loadAdminData(){try{const d=await getAdminStats();const s=d.stats;document.getElementById('adminUsersVal').textContent=s.totalUsers;document.getElementById('adminTotalListingsVal').textContent=s.totalLand+s.totalEquipment+s.totalLabour+s.totalProduce;document.getElementById('adminRevenueVal').textContent='₹'+s.totalRevenue.toLocaleString();document.getElementById('adminBookingsVal').textContent=s.totalBookings;document.getElementById('adminPendingLand').textContent=s.pendingLand;document.getElementById('adminPendingEquip').textContent=s.pendingEquip;document.getElementById('adminPendingLabour').textContent=s.pendingLabour;document.getElementById('adminPendingProduce').textContent=s.pendingProduce;}catch(e){console.error('Admin stats error:',e);}}
async function loadAdminPending(){const c=document.getElementById('adminPendingList');if(!c)return;try{const d=await getPendingListings();let h='';const ri=(items,type,label)=>{if(!items.length)return'';return `<h3 style="font-size:16px;margin:16px 0 8px;">${escapeHtml(label)} (${items.length})</h3>`+items.map(i=>{const nm=escapeHtml(i.title||i.name||i.crop_name||i.worker_name);const loc=escapeHtml(i.location||'');return `<div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center;"><div><strong>${nm}</strong><br><span style="color:#64748b;font-size:13px;">${loc}</span></div><div style="display:flex;gap:6px;"><button onclick="adminApprove('${escapeHtml(type)}',${i.id},'approved')" style="background:#16a34a;color:#fff;border:none;padding:6px 12px;border-radius:6px;cursor:pointer;font-size:12px;">Approve</button><button onclick="adminApprove('${escapeHtml(type)}',${i.id},'rejected')" style="background:#dc2626;color:#fff;border:none;padding:6px 12px;border-radius:6px;cursor:pointer;font-size:12px;">Reject</button></div></div>`;}).join('');};h+=ri(d.land,'land','Land');h+=ri(d.equipment,'equipment','Equipment');h+=ri(d.labour,'labour','Labour');h+=ri(d.produce,'produce','Produce');c.innerHTML=h||'<p style="padding:24px;text-align:center;color:#64748b;">No pending listings.</p>';}catch(e){c.innerHTML='<p style="color:#dc2626;">Error.</p>';}}
async function adminApprove(type,id,status){try{await approveListing(type,id,status);showToast('Listing '+status+'!');loadAdminPending();loadAdminData();}catch(e){showToast('Error: '+e.message);}}
async function loadAdminUsers(){const c=document.getElementById('adminUsersList');if(!c)return;try{const d=await getAdminUsers();c.innerHTML=d.users.map(u=>{const nm=escapeHtml(u.username),em=escapeHtml(u.email),rl=escapeHtml(u.role);return `<div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center;"><div><strong>${nm}</strong><br><span style="color:#64748b;font-size:13px;">${em} ${rl}</span></div><button onclick="if(confirm('Delete?'))deleteUser(${u.id}).then(()=>{showToast('Deleted');loadAdminUsers();})" style="background:#dc2626;color:#fff;border:none;padding:4px 10px;border-radius:6px;cursor:pointer;font-size:12px;">Delete</button></div>`;}).join('');}catch(e){c.innerHTML='<p style="color:#dc2626;">Error.</p>';}}

// ===== AUTH HANDLERS =====
document.getElementById('form-signin')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const email=document.getElementById('signin-email').value.trim();const password=document.getElementById('signin-password').value;const data=await signin({email,password});setToken(data.token);setUser(data.user);document.getElementById('nav-signin-btn').style.display='none';document.getElementById('nav-signup-btn').style.display='none';document.getElementById('nav-user-menu').style.display='block';document.getElementById('nav-user-name').textContent=data.user.username;showToast('Welcome, '+data.user.username+'!');navigateTo('view-home');}catch(e){showToast('Sign in error: '+e.message);}});
document.getElementById('form-signup')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const data=await signup({username:document.getElementById('signup-username').value.trim(),email:document.getElementById('signup-email').value.trim(),password:document.getElementById('signup-password').value,role:document.getElementById('signup-role').value,phone:document.getElementById('signup-phone').value.trim(),location:document.getElementById('signup-location').value.trim()});setToken(data.token);setUser(data.user);document.getElementById('nav-signin-btn').style.display='none';document.getElementById('nav-signup-btn').style.display='none';document.getElementById('nav-user-menu').style.display='block';document.getElementById('nav-user-name').textContent=data.user.username;showToast('Welcome, '+data.user.username+'!');navigateTo('view-home');}catch(e){showToast('Sign up error: '+e.message);}});
document.getElementById('btn-signout')?.addEventListener('click',async()=>{try{await signout();}catch(e){}clearToken();document.getElementById('nav-signin-btn').style.display='';document.getElementById('nav-signup-btn').style.display='';document.getElementById('nav-user-menu').style.display='none';showToast('Signed out.');navigateTo('view-home');});

// ===== RESTORE AUTH ON LOAD =====
(async function(){const token=getToken();if(token){try{const data=await fetchMe();setUser(data.user);document.getElementById('nav-signin-btn').style.display='none';document.getElementById('nav-signup-btn').style.display='none';document.getElementById('nav-user-menu').style.display='block';document.getElementById('nav-user-name').textContent=data.user.username;}catch(e){clearToken();}}})();
