-- Migration 003 — Smart Matching, Provider Availability & Extended Catalogue

-- Equipment Listing extended catalogue fields
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS brand               TEXT;
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS model               TEXT;
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS year                INTEGER;
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS registration_number TEXT;
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS attachments_list    TEXT;
ALTER TABLE equipment_listings ADD COLUMN IF NOT EXISTS max_distance        INTEGER DEFAULT 25;

-- Labour Services extended catalogue fields
ALTER TABLE labour_services ADD COLUMN IF NOT EXISTS max_distance        INTEGER DEFAULT 25;
ALTER TABLE labour_services ADD COLUMN IF NOT EXISTS crop_experience     TEXT;
ALTER TABLE labour_services ADD COLUMN IF NOT EXISTS work_types           TEXT;

-- Service Bookings lifecycle and farm info fields
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS farm_for           TEXT DEFAULT 'my_farm';
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS farm_details       TEXT;
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS otp_code           TEXT;
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS otp_verified       INTEGER DEFAULT 0;
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS payment_status     TEXT DEFAULT 'unpaid';
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS rating             INTEGER;
ALTER TABLE service_bookings ADD COLUMN IF NOT EXISTS review_comment      TEXT;

-- Regular Bookings lifecycle fields
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS farm_for           TEXT DEFAULT 'my_farm';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS otp_code           TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS otp_verified       INTEGER DEFAULT 0;

-- Provider Availability Calendar table
CREATE TABLE IF NOT EXISTS provider_availability (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date        TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'unavailable' CHECK(status IN ('available','unavailable')),
  note        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(provider_id, date)
);

CREATE INDEX IF NOT EXISTS idx_prov_avail_user_date ON provider_availability(provider_id, date);
