/* ═══════════════════════════════════════════
   Krishi Sangam — Postgres schema (Supabase)
   Translated from the original SQLite schema.
   Run in the Supabase SQL Editor, or:
     psql "$DATABASE_URL" -f sql/schema.sql
   ═══════════════════════════════════════════ */

/* ── Users ── */
CREATE TABLE IF NOT EXISTS users (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         TEXT    NOT NULL UNIQUE,
  email            TEXT    NOT NULL UNIQUE,
  password_hash    TEXT    NOT NULL,
  role             TEXT    NOT NULL DEFAULT 'farmer'
                             CHECK(role IN ('farmer','owner','labourer','admin')),
  phone            TEXT,
  location         TEXT,
  bio              TEXT,
  skills           TEXT,
  avatar_url       TEXT,
  gender           TEXT,
  dob              TEXT,
  govt_id_url      TEXT,
  id_type          TEXT,
  id_number        TEXT,
  village          TEXT,
  taluka           TEXT,
  district         TEXT,
  state            TEXT,
  labour_category  TEXT,
  skill_level      TEXT,
  bank_account     TEXT,
  ifsc             TEXT,
  upi_id           TEXT,
  farm_size        TEXT,
  farm_lat         DOUBLE PRECISION,
  farm_lng         DOUBLE PRECISION,
  phone_verified   INTEGER DEFAULT 0 CHECK(phone_verified IN (0,1)),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Sessions ── */
CREATE TABLE IF NOT EXISTS sessions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token      TEXT   NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── OTP Verifications ── */
CREATE TABLE IF NOT EXISTS otp_verifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone      TEXT   NOT NULL,
  otp        TEXT   NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Land Listings ── */
CREATE TABLE IF NOT EXISTS land_listings (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id          BIGINT NOT NULL REFERENCES users(id),
  title             TEXT   NOT NULL,
  description       TEXT,
  area_acres        DOUBLE PRECISION NOT NULL,
  lease_type        TEXT   DEFAULT 'Per Season'
                            CHECK(lease_type IN ('Per Season','Per Month','Per Year')),
  price_per_season  INTEGER,
  price_per_month   INTEGER,
  price_per_year    INTEGER,
  location          TEXT   NOT NULL,
  district          TEXT,
  state             TEXT,
  soil_type         TEXT,
  water_source      TEXT,
  crop_history      TEXT,
  photo_url         TEXT,
  status            TEXT   DEFAULT 'pending'
                            CHECK(status IN ('pending','approved','rejected')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Equipment Listings ── */
CREATE TABLE IF NOT EXISTS equipment_listings (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id       BIGINT NOT NULL REFERENCES users(id),
  name           TEXT   NOT NULL,
  type           TEXT   NOT NULL,
  description    TEXT,
  price_per_hour INTEGER,
  price_per_day  INTEGER,
  deposit        INTEGER,
  location       TEXT   NOT NULL,
  district       TEXT,
  state          TEXT,
  with_operator  INTEGER DEFAULT 0 CHECK(with_operator IN (0,1)),
  photo_url      TEXT,
  status         TEXT   DEFAULT 'pending'
                         CHECK(status IN ('pending','approved','rejected')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Labour Services ── */
CREATE TABLE IF NOT EXISTS labour_services (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id        BIGINT NOT NULL REFERENCES users(id),
  title            TEXT   NOT NULL,
  description      TEXT,
  skills           TEXT,
  experience_years INTEGER DEFAULT 0,
  daily_rate       INTEGER,
  hourly_rate      INTEGER,
  location         TEXT   NOT NULL,
  district         TEXT,
  state            TEXT,
  availability     TEXT   DEFAULT 'available'
                           CHECK(availability IN ('available','busy','offline')),
  photo_url        TEXT,
  status           TEXT   DEFAULT 'pending'
                           CHECK(status IN ('pending','approved','rejected')),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Produce Listings ── */
CREATE TABLE IF NOT EXISTS produce_listings (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id      BIGINT NOT NULL REFERENCES users(id),
  crop_name      TEXT   NOT NULL,
  description    TEXT,
  quantity       DOUBLE PRECISION NOT NULL,
  unit           TEXT   DEFAULT 'kg' CHECK(unit IN ('kg','quintal','tonne','piece')),
  price_per_unit INTEGER NOT NULL,
  location       TEXT   NOT NULL,
  district       TEXT,
  state          TEXT,
  quality_grade  TEXT   DEFAULT 'A',
  photo_url      TEXT,
  status         TEXT   DEFAULT 'pending'
                         CHECK(status IN ('pending','approved','rejected')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Bookings ── */
CREATE TABLE IF NOT EXISTS bookings (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booker_id      BIGINT NOT NULL REFERENCES users(id),
  owner_id       BIGINT NOT NULL REFERENCES users(id),
  listing_type   TEXT   NOT NULL CHECK(listing_type IN ('land','equipment','labour','produce')),
  listing_id     BIGINT NOT NULL,
  listing_title  TEXT,
  start_date     TEXT,
  end_date       TEXT,
  quantity       DOUBLE PRECISION DEFAULT 1,
  total_price    INTEGER NOT NULL,
  status         TEXT   DEFAULT 'pending'
                         CHECK(status IN ('pending','confirmed','active','completed','cancelled')),
  payment_status TEXT   DEFAULT 'unpaid'
                         CHECK(payment_status IN ('unpaid','escrow','released','refunded')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Service Bookings (Agricultural Services & Labour Teams) ── */
CREATE TABLE IF NOT EXISTS service_bookings (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id),
  kind         TEXT   NOT NULL DEFAULT 'service'
                         CHECK(kind IN ('labour_team','service')),
  category     TEXT,
  service_name TEXT,
  num_workers  INTEGER,
  days         INTEGER,
  team_type    TEXT,
  skill_level  TEXT,
  start_date   TEXT,
  location     TEXT,
  lat          DOUBLE PRECISION,
  lng          DOUBLE PRECISION,
  description  TEXT,
  price        INTEGER,
  status       TEXT   DEFAULT 'pending'
                       CHECK(status IN ('pending','confirmed','completed','cancelled')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Messages ── */
CREATE TABLE IF NOT EXISTS messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id   BIGINT NOT NULL REFERENCES users(id),
  receiver_id BIGINT NOT NULL REFERENCES users(id),
  booking_id  BIGINT REFERENCES bookings(id),
  content     TEXT   NOT NULL,
  is_read     INTEGER DEFAULT 0 CHECK(is_read IN (0,1)),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Payments (Escrow Ledger) ── */
CREATE TABLE IF NOT EXISTS payments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      BIGINT NOT NULL REFERENCES bookings(id),
  payer_id        BIGINT NOT NULL REFERENCES users(id),
  payee_id        BIGINT NOT NULL REFERENCES users(id),
  amount          INTEGER NOT NULL,
  status          TEXT   DEFAULT 'held'
                          CHECK(status IN ('held','released','refunded')),
  method          TEXT   DEFAULT 'upi',
  transaction_ref TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Reviews ── */
CREATE TABLE IF NOT EXISTS reviews (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reviewer_id BIGINT NOT NULL REFERENCES users(id),
  reviewee_id BIGINT NOT NULL REFERENCES users(id),
  booking_id  BIGINT NOT NULL REFERENCES bookings(id),
  rating      INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

/* ── Indexes ── */
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_land_owner ON land_listings(owner_id);
CREATE INDEX IF NOT EXISTS idx_land_status ON land_listings(status);
CREATE INDEX IF NOT EXISTS idx_equip_owner ON equipment_listings(owner_id);
CREATE INDEX IF NOT EXISTS idx_equip_status ON equipment_listings(status);
CREATE INDEX IF NOT EXISTS idx_labour_worker ON labour_services(worker_id);
CREATE INDEX IF NOT EXISTS idx_labour_status ON labour_services(status);
CREATE INDEX IF NOT EXISTS idx_produce_seller ON produce_listings(seller_id);
CREATE INDEX IF NOT EXISTS idx_produce_status ON produce_listings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_booker ON bookings(booker_id);
CREATE INDEX IF NOT EXISTS idx_bookings_owner ON bookings(owner_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver ON messages(receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_booking ON messages(booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_service_bookings_user ON service_bookings(user_id);
