/* ═══════════════════════════════════════════
   Krishi Sangam — server/routes/agriServices.js
   (Agricultural Service Listings CRUD & Search API)
   ═══════════════════════════════════════════ */

const express = require('express');
const { getDb } = require('../db');
const { authenticateToken, requireRole } = require('../middleware/auth');

const router = express.Router();

/* Ensure table exists */
async function ensureAgriTable(db) {
  await db.exec(`
    CREATE TABLE IF NOT EXISTS agri_service_listings (
      id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      provider_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title              TEXT NOT NULL,
      category           TEXT NOT NULL,
      sub_category       TEXT,
      description        TEXT,
      price              INTEGER NOT NULL,
      pricing_type       TEXT DEFAULT 'per_acre' CHECK(pricing_type IN ('per_acre','per_hour','per_day','fixed')),
      equipment_included TEXT,
      service_area_km    INTEGER DEFAULT 25,
      location           TEXT NOT NULL,
      district           TEXT,
      state              TEXT,
      lat                DOUBLE PRECISION,
      lng                DOUBLE PRECISION,
      availability       TEXT DEFAULT 'available' CHECK(availability IN ('available','busy','offline')),
      photo_url          TEXT,
      status             TEXT DEFAULT 'approved' CHECK(status IN ('pending','approved','rejected')),
      created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS idx_agri_service_provider ON agri_service_listings(provider_id);
    CREATE INDEX IF NOT EXISTS idx_agri_service_category ON agri_service_listings(category);
    CREATE INDEX IF NOT EXISTS idx_agri_service_status ON agri_service_listings(status);
  `);
}

/* ── GET /api/agri-services — List all approved services ── */
router.get('/', async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);

    const { search, category, district, state, pricing_type, min_price, max_price } = req.query;

    let query = `
      SELECT s.*, u.username as provider_name, u.phone as provider_phone, u.avatar_url as provider_avatar
      FROM agri_service_listings s
      JOIN users u ON s.provider_id = u.id
      WHERE s.status = 'approved'
    `;
    const params = [];

    if (search) {
      query += ` AND (s.title ILIKE ? OR s.category ILIKE ? OR s.description ILIKE ? OR s.location ILIKE ? OR s.equipment_included ILIKE ?)`;
      params.push(`%${search}%`, `%${search}%`, `%${search}%`, `%${search}%`, `%${search}%`);
    }
    if (category && category !== 'All') {
      query += ` AND s.category ILIKE ?`;
      params.push(`%${category}%`);
    }
    if (district) {
      query += ` AND s.district ILIKE ?`;
      params.push(`%${district}%`);
    }
    if (state) {
      query += ` AND s.state ILIKE ?`;
      params.push(`%${state}%`);
    }
    if (pricing_type) {
      query += ` AND s.pricing_type = ?`;
      params.push(pricing_type);
    }
    if (min_price) {
      query += ` AND s.price >= ?`;
      params.push(Number(min_price));
    }
    if (max_price) {
      query += ` AND s.price <= ?`;
      params.push(Number(max_price));
    }

    query += ` ORDER BY s.created_at DESC`;
    const listings = await db.prepare(query).all(...params);

    // Fetch review ratings stats per provider
    for (const item of listings) {
      const stats = await db.prepare(`
        SELECT COALESCE(AVG(rating), 0) as avg_rating, COUNT(*) as total_reviews
        FROM reviews
        WHERE reviewee_id = ?
      `).get(item.provider_id);
      item.avg_rating = Math.round((stats?.avg_rating || 5) * 10) / 10;
      item.total_reviews = stats?.total_reviews || 0;
    }

    res.json({ listings, count: listings.length });
  } catch (err) {
    console.error('Get agri services error:', err);
    res.status(500).json({ error: 'Server error fetching agricultural services.' });
  }
});

/* ── GET /api/agri-services/my — Logged in provider listings ── */
router.get('/my', authenticateToken, async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);
    const listings = await db.prepare(
      `SELECT * FROM agri_service_listings WHERE provider_id = ? ORDER BY created_at DESC`
    ).all(req.user.id);
    res.json({ listings, count: listings.length });
  } catch (err) {
    console.error('Get my agri services error:', err);
    res.status(500).json({ error: 'Server error.' });
  }
});

/* ── GET /api/agri-services/:id — Single detail ── */
router.get('/:id', async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);
    const listing = await db.prepare(`
      SELECT s.*, u.username as provider_name, u.phone as provider_phone, u.bio as provider_bio
      FROM agri_service_listings s
      JOIN users u ON s.provider_id = u.id
      WHERE s.id = ?
    `).get(req.params.id);

    if (!listing) return res.status(404).json({ error: 'Service listing not found.' });

    const stats = await db.prepare(`
      SELECT COALESCE(AVG(rating), 0) as avg_rating, COUNT(*) as total_reviews
      FROM reviews WHERE reviewee_id = ?
    `).get(listing.provider_id);

    listing.avg_rating = Math.round((stats?.avg_rating || 5) * 10) / 10;
    listing.total_reviews = stats?.total_reviews || 0;

    res.json({ listing });
  } catch (err) {
    res.status(500).json({ error: 'Server error.' });
  }
});

/* ── POST /api/agri-services — Create Listing ── */
router.post('/', authenticateToken, async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);

    const {
      title, category, sub_category, description, price, pricing_type,
      equipment_included, service_area_km, location, district, state,
      lat, lng, photo_url
    } = req.body;

    if (!title || !category || !price || !location) {
      return res.status(400).json({ error: 'Title, category, price, and location are required.' });
    }

    const result = await db.prepare(`
      INSERT INTO agri_service_listings (
        provider_id, title, category, sub_category, description, price, pricing_type,
        equipment_included, service_area_km, location, district, state, lat, lng,
        photo_url, status
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'approved')
    `).run(
      req.user.id,
      title,
      category,
      sub_category || null,
      description || null,
      Number(price),
      pricing_type || 'per_acre',
      equipment_included || null,
      service_area_km ? Number(service_area_km) : 25,
      location,
      district || null,
      state || null,
      lat ? Number(lat) : null,
      lng ? Number(lng) : null,
      photo_url || null
    );

    const listing = await db.prepare('SELECT * FROM agri_service_listings WHERE id = ?').get(result.lastInsertRowid);
    res.status(201).json({ message: 'Agricultural service listing created successfully!', listing });
  } catch (err) {
    console.error('Create agri service error:', err);
    res.status(500).json({ error: 'Server error creating service listing.' });
  }
});

/* ── PUT /api/agri-services/:id — Update ── */
router.put('/:id', authenticateToken, async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);

    const listing = await db.prepare('SELECT * FROM agri_service_listings WHERE id = ?').get(req.params.id);
    if (!listing) return res.status(404).json({ error: 'Listing not found.' });

    if (listing.provider_id !== req.user.id && req.user.role !== 'admin') {
      return res.status(403).json({ error: 'Not authorized to update this listing.' });
    }

    const {
      title, category, sub_category, description, price, pricing_type,
      equipment_included, service_area_km, location, district, state,
      availability, status, photo_url
    } = req.body;

    await db.prepare(`
      UPDATE agri_service_listings
      SET title = COALESCE(?, title),
          category = COALESCE(?, category),
          sub_category = COALESCE(?, sub_category),
          description = COALESCE(?, description),
          price = COALESCE(?, price),
          pricing_type = COALESCE(?, pricing_type),
          equipment_included = COALESCE(?, equipment_included),
          service_area_km = COALESCE(?, service_area_km),
          location = COALESCE(?, location),
          district = COALESCE(?, district),
          state = COALESCE(?, state),
          availability = COALESCE(?, availability),
          status = COALESCE(?, status),
          photo_url = COALESCE(?, photo_url),
          updated_at = NOW()
      WHERE id = ?
    `).run(
      title || null, category || null, sub_category || null, description || null,
      price ? Number(price) : null, pricing_type || null, equipment_included || null,
      service_area_km ? Number(service_area_km) : null, location || null,
      district || null, state || null, availability || null, status || null,
      photo_url || null, req.params.id
    );

    const updated = await db.prepare('SELECT * FROM agri_service_listings WHERE id = ?').get(req.params.id);
    res.json({ message: 'Service updated.', listing: updated });
  } catch (err) {
    console.error('Update agri service error:', err);
    res.status(500).json({ error: 'Server error updating service.' });
  }
});

/* ── DELETE /api/agri-services/:id — Delete ── */
router.delete('/:id', authenticateToken, async (req, res) => {
  try {
    const db = getDb();
    await ensureAgriTable(db);

    const listing = await db.prepare('SELECT * FROM agri_service_listings WHERE id = ?').get(req.params.id);
    if (!listing) return res.status(404).json({ error: 'Listing not found.' });

    if (listing.provider_id !== req.user.id && req.user.role !== 'admin') {
      return res.status(403).json({ error: 'Not authorized to delete this listing.' });
    }

    await db.prepare('DELETE FROM agri_service_listings WHERE id = ?').run(req.params.id);
    res.json({ message: 'Service listing deleted.' });
  } catch (err) {
    console.error('Delete agri service error:', err);
    res.status(500).json({ error: 'Server error deleting service.' });
  }
});

module.exports = router;
