/* ═══════════════════════════════════════════
   KrishiSetu — server/migrate.js
   One-time migration: SQLite (server/krishisetu.db) → Postgres (DATABASE_URL)
   Preserves all IDs and foreign-key relationships.

   Usage:
     1. Create the Postgres schema first:  psql "$DATABASE_URL" -f sql/schema.sql
        (or paste sql/schema.sql into the Supabase SQL editor)
     2. node migrate.js
   ═══════════════════════════════════════════ */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const Database = require('better-sqlite3'); // reads the OLD local SQLite db
const { Pool } = require('pg');

const SQLITE_PATH = path.join(__dirname, 'krishisetu.db');

// Tables in FK-safe order (parents before children)
const TABLES = [
  'users',
  'sessions',
  'otp_verifications',
  'land_listings',
  'equipment_listings',
  'labour_services',
  'produce_listings',
  'bookings',
  'service_bookings',
  'messages',
  'payments',
  'reviews'
];

async function main() {
  if (!fs.existsSync(SQLITE_PATH)) {
    console.log('ℹ️  No local SQLite db found at server/krishisetu.db — nothing to migrate.');
    return;
  }
  if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL is not set. Add it to server/.env (see .env.example).');
    process.exit(1);
  }

  const sqlite = new Database(SQLITE_PATH, { readonly: true });
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }
  });

  let total = 0;

  try {
    for (const table of TABLES) {
      // Skip tables that don't exist in the old db (e.g. reviews may be empty/new)
      const exists = sqlite.prepare(
        "SELECT name FROM sqlite_master WHERE type='table' AND name = ?"
      ).get(table);
      if (!exists) {
        console.log(`⏭  ${table}: not in SQLite, skipping`);
        continue;
      }

      const rows = sqlite.prepare(`SELECT * FROM ${table}`).all();
      if (rows.length === 0) {
        console.log(`⏭  ${table}: 0 rows, skipping`);
        continue;
      }

      // Use column names from the SQLite result so the Postgres table matches
      const cols = Object.keys(rows[0]);
      const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');

      // Preserve original IDs (important for FK relationships).
      // Columns are GENERATED BY DEFAULT AS IDENTITY, so explicit IDs are allowed directly.
      const finalSql = `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${placeholders})`;

      // Insert rows one-by-one in a single transaction
      const client2 = await pool.connect();
      try {
        await client2.query('BEGIN');
        for (const row of rows) {
          const values = cols.map((c) => row[c] ?? null);
          await client2.query(finalSql, values);
        }
        await client2.query('COMMIT');
        console.log(`✅ ${table}: ${rows.length} rows migrated`);
        total += rows.length;
      } catch (err) {
        await client2.query('ROLLBACK');
        throw err;
      } finally {
        client2.release();
      }
    }

    // Advance identity sequences so future auto-generated IDs don't collide with migrated ones
    const seqClient = await pool.connect();
    try {
      for (const table of TABLES) {
        await seqClient.query(
          `SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 1))`,
          [table]
        );
      }
      console.log('🔢 Identity sequences synced.');
    } finally {
      seqClient.release();
    }

    console.log(`\n🎉 Migration complete! ${total} rows copied to Postgres.`);
  } catch (err) {
    console.error('❌ Migration failed:', err.message);
    process.exitCode = 1;
  } finally {
    sqlite.close();
    await pool.end();
  }
}

main();
